language: node_js
install:
  - cd ./functions && npm ci
  - cd ../ && npm ci
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
jobs:
  include:
  - stage: Test
    script:
    - commitlint-travis
  - stage: Deploy Site
    script:
    - npm run build
    deploy:
      skip_cleanup: true
      provider: firebase
      token:
        secure: hW98n3yBMJ6javijRCrOI9F1aKtxIjiwh/HsXZzq4YeWn78v9VcdTYU74fidHdk9/uq/uZd3Iih10zmRaEzzpP5wLtBGn2KTOntz5GkzCa+azii9pWEycRitODlJYsZEM+Q7nBNh9zpRYiEVdFicIeSXWB6oC4ZaHjDmxUNLV8V1Uzvtp/IAGA4Pf95OOXm4aRt3PrI7OY22TmRLVdZGWwscSwpLQAuHGKozvYgtWE2QtsH/lNCmnxUzcJmm1pklC8aD65opuva4t6ceuey9oYqFtJfiPNmdYQk6aeemPHvHul27Vb0UVYRTGW6XKUkmIUBIRsXMdWSQNvGOrGHEcQeAuP17PH+20JpiqnmbYs32RD++92Z7q9N9cZruQ9VIu/aAfTjlq0Je0udYwXefPb+fNdJx87oM5zaI4Ui40wgL31x+ymhqJ4iLvno2TSkrzqL7BFiZtkvpu+rs4Jq2Cnwjgbl8/FAtuxtOjfINZZa9dwb8yrRSb7XO42s302sk/0wwGtefeF3KRdDeAbghRGV77wO4HKJA+MeYo58HQv9M/P9xh4gtnIziV2P+0sAf1CRnN9rJi4O8LNVcZCITQqtE+CtJib9QOHznIatb3Wu1Iqdvfn0BcxI+gz1ZFeFwr8UmOdu8bqKaElyyxNfsDcBhpTCV7C/yzqK93vPasBw=
