name: CI Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Install, test and build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Install site dependencies
        run: npm ci

      - name: Install function dependencies
        run: cd functions && npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "default"
