name: CI Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Install, test and build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Install site dependencies
        run: npm ci

      - name: Install function dependencies
        run: cd functions && npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Archive www build
        uses: actions/upload-artifact@master
        with:
          name: www
          path: www

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Download www build
        uses: actions/download-artifact@master
        with:
          name: www
          path: www

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: "default"
